[project]
name = "sound-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pyaudio>=0.2.14",
    "requests>=2.32.4",
    "flask>=3.0.0",
    # "RPi.GPIO>=0.7.1",
    "rpi",
]

[tool.uv.sources]
rpi = { git = "https://github.com/nosix/raspberry-gpio-emulator" }
